name: DrcomoGuiBinder
version: '${project.version}'
main: cn.drcomo.drcomoguibinder.DrcomoGuiBinder
api-version: '1.20'
depend:
  - DrcomoCoreLib
commands:
  guibinder:
    description: 'DrcomoGuiBinder 主指令'
    usage: '/<command> help'
    aliases: [dgb, drgb]
    permission: drcomoguibinder.command
